services:
  backend:
    container_name: saire-api
    image: mcr.microsoft.com/dotnet/sdk:10.0
    volumes:
        - ./backend:/app
        - /app/bin
        - /app/obj
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    command: dotnet watch run --project backend.csproj --urls=http://0.0.0.0:5000

  frontend:
    container_name: saire-front
    image: node:24
    volumes:
      - ./frontend/frontend:/app
      # Volume anônimo para não sobrescrever os nodes_modules do container com os do host
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    # command: sh -c "npm install && npm run dev"
    command: npx next dev --webpack -H 0.0.0.0
    # command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --webpack"
    # depends_on:
    #   - backend
